In [1]:
!pip install pandas

In [2]:
import pandas as pd

In [3]:
!pip install scikit-learn

In [4]:
from sklearn.preprocessing import StandardScaler

In [5]:
scaler=StandardScaler()

In [6]:
df=pd.read_csv('Social_Network_Ads.csv')
df

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [9]:
df.drop('User ID', axis=1, inplace=True)

In [11]:
df['Gender']=df['Gender'].replace({'Male':0,'Female':1})

C:\Users\anish\AppData\Local\Temp\ipykernel_24588\3195947867.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Gender']=df['Gender'].replace({'Male':0,'Female':1})


In [12]:
df

Gender  Age  EstimatedSalary  Purchased
0         0   19            19000          0
1         0   35            20000          0
2         1   26            43000          0
3         1   27            57000          0
4         0   19            76000          0
..      ...  ...              ...        ...
395       1   46            41000          1
396       0   51            23000          1
397       1   50            20000          1
398       0   36            33000          0
399       1   49            36000          1

[400 rows x 4 columns]

In [13]:
x=df.drop('Purchased',axis=1)

In [14]:
y=df['Purchased']

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42)

In [17]:
x_train

Gender  Age  EstimatedSalary
258       1   58            95000
177       0   25            22000
119       0   41            59000
194       0   28            89000
229       1   42            80000
..      ...  ...              ...
71        1   24            27000
106       1   26            35000
270       1   43           133000
348       0   39            77000
102       1   32            86000

[268 rows x 3 columns]

In [18]:
y_test

209    0
280    1
33     0
210    1
93     0
      ..
332    0
167    0
245    1
311    1
145    0
Name: Purchased, Length: 132, dtype: int64

In [26]:
x_train_scaled=scaler.fit_transform(x_train)
x_train_scaled

array([[ 0.97785703,  2.0052225 ,  0.72479792],
       [-1.02264438, -1.22740379, -1.43119212],
       [-1.02264438,  0.33993017, -0.33843005],
       [-1.02264438, -0.93352867,  0.54759326],
       [ 0.97785703,  0.43788855,  0.28178627],
       [ 0.97785703,  0.43788855,  1.10874135],
       [ 0.97785703,  0.82972204,  0.75433203],
       [ 0.97785703,  0.92768041,  1.2564119 ],
       [ 0.97785703, -0.44373681, -1.25398746],
       [-1.02264438, -1.81515402, -1.34258979],
       [-1.02264438,  1.12359715,  0.54759326],
       [ 0.97785703, -0.63965355, -1.63793089],
       [ 0.97785703, -0.73761192,  0.25225216],
       [-1.02264438,  1.02563878,  2.08336699],
       [ 0.97785703, -0.54169518,  1.37454834],
       [ 0.97785703, -0.05190332,  0.01597928],
       [ 0.97785703, -1.91311239,  0.45899093],
       [ 0.97785703,  0.43788855,  0.25225216],
       [ 0.97785703, -1.03148704,  0.39992271],
       [-1.02264438,  0.2419718 , -0.16122538],
       [-1.02264438,  1.90726413,  0.104

In [28]:
x_train

Gender  Age  EstimatedSalary
258       1   58            95000
177       0   25            22000
119       0   41            59000
194       0   28            89000
229       1   42            80000
..      ...  ...              ...
71        1   24            27000
106       1   26            35000
270       1   43           133000
348       0   39            77000
102       1   32            86000

[268 rows x 3 columns]

In [21]:
type(scaler.transform(x_test))

numpy.ndarray

In [27]:
x_test_scaled=scaler.transform(x_test)
x_test_scaled

array([[ 0.97785703,  0.82972204, -1.43119212],
       [ 0.97785703,  2.10318088,  0.51805915],
       [ 0.97785703, -0.93352867, -0.7814417 ],
       [ 0.97785703,  1.02563878,  0.75433203],
       [ 0.97785703, -0.8355703 , -1.25398746],
       [ 0.97785703, -0.73761192, -0.24982772],
       [ 0.97785703,  0.92768041,  1.07920724],
       [ 0.97785703, -0.8355703 ,  0.3703886 ],
       [-1.02264438,  0.2419718 ,  0.13411572],
       [-1.02264438,  0.43788855, -0.16122538],
       [ 0.97785703, -0.24782006, -0.16122538],
       [ 0.97785703,  1.51543064, -1.0767828 ],
       [ 0.97785703, -1.42332053, -0.66330526],
       [ 0.97785703, -1.71719565, -1.40165801],
       [-1.02264438, -0.73761192,  0.48852504],
       [-1.02264438, -0.24782006,  1.10874135],
       [ 0.97785703,  1.41747227, -0.95864636],
       [ 0.97785703,  0.82972204,  0.10458161],
       [-1.02264438,  0.14401343, -0.84050992],
       [-1.02264438,  1.80930576, -0.30889594],
       [ 0.97785703, -1.5212789 , -1.283

In [29]:
x_train_scaled

array([[ 0.97785703,  2.0052225 ,  0.72479792],
       [-1.02264438, -1.22740379, -1.43119212],
       [-1.02264438,  0.33993017, -0.33843005],
       [-1.02264438, -0.93352867,  0.54759326],
       [ 0.97785703,  0.43788855,  0.28178627],
       [ 0.97785703,  0.43788855,  1.10874135],
       [ 0.97785703,  0.82972204,  0.75433203],
       [ 0.97785703,  0.92768041,  1.2564119 ],
       [ 0.97785703, -0.44373681, -1.25398746],
       [-1.02264438, -1.81515402, -1.34258979],
       [-1.02264438,  1.12359715,  0.54759326],
       [ 0.97785703, -0.63965355, -1.63793089],
       [ 0.97785703, -0.73761192,  0.25225216],
       [-1.02264438,  1.02563878,  2.08336699],
       [ 0.97785703, -0.54169518,  1.37454834],
       [ 0.97785703, -0.05190332,  0.01597928],
       [ 0.97785703, -1.91311239,  0.45899093],
       [ 0.97785703,  0.43788855,  0.25225216],
       [ 0.97785703, -1.03148704,  0.39992271],
       [-1.02264438,  0.2419718 , -0.16122538],
       [-1.02264438,  1.90726413,  0.104

In [31]:
x_train_scaled=pd.DataFrame(x_train_scaled,columns=x_train.columns)
x_test_scaled=pd.DataFrame(x_test_scaled,columns=x_test.columns)

In [32]:
x_train_scaled

Gender       Age  EstimatedSalary
0    0.977857  2.005223         0.724798
1   -1.022644 -1.227404        -1.431192
2   -1.022644  0.339930        -0.338430
3   -1.022644 -0.933529         0.547593
4    0.977857  0.437889         0.281786
..        ...       ...              ...
263  0.977857 -1.325362        -1.283522
264  0.977857 -1.129445        -1.047249
265  0.977857  0.535847         1.847094
266 -1.022644  0.144013         0.193184
267  0.977857 -0.541695         0.458991

[268 rows x 3 columns]

In [41]:
np.round(x_train.describe(),2)

Gender     Age  EstimatedSalary
count  268.00  268.00           268.00
mean     0.51   37.53         70458.96
std      0.50   10.23         33922.50
min      0.00   18.00         15000.00
25%      0.00   30.00         44000.00
50%      1.00   37.00         71000.00
75%      1.00   45.00         88000.00
max      1.00   60.00        150000.00

In [37]:
!pip install numpy

In [39]:
import numpy as np

In [40]:
np.round(x_train_scaled.describe(),2)

Gender     Age  EstimatedSalary
count  268.00  268.00           268.00
mean     0.00   -0.00             0.00
std      1.00    1.00             1.00
min     -1.02   -1.91            -1.64
25%     -1.02   -0.74            -0.78
50%      0.98   -0.05             0.02
75%      0.98    0.73             0.52
max      0.98    2.20             2.35